# Data curation phase of EvalPerf
CURATION_TIMEOUT_PER_TEST_SECOND = 20
CURATION_MEMORY_LIMIT_GB = 4
MIN_REQUIRED_NUM_INSTRUCTION = 10000
CURATION_PROFILE_ROUNDS = 1

# Evaluation phase of EvalPerf
EVALUATION_TIMEOUT_SECOND_PER_TEST = 40
EVALUATION_MEMORY_LIMIT_GB = CURATION_MEMORY_LIMIT_GB
EVALUATION_PROFILE_ROUNDS = CURATION_PROFILE_ROUNDS
