# General
PROFILE_ROUNDS = 1
PER_PROC_RAM_LIMIT_GB = 12

# Data curation phase of EvalPerf
CURATION_TIMEOUT_PER_TEST_SECOND = 20
MIN_REQUIRED_NUM_INSTRUCTION = 10000

# Evaluation phase of EvalPerf
EVALUATION_TIMEOUT_SECOND_PER_TEST = 60
